on: 
  pull_request:
    branches:
      - main

env:
  TEST_TAG: wgwergwegwer/exlex-nginx:test
  DEPLOY_TAG: wgwergwegwer/exlex-nginx:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current branch
        uses: actions/checkout@v3

      - name: connect tools to build image
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build test image and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          load: false
          push: false
          tags: ${{ env.TEST_TAG }}
          outputs: type=docker,dest=/tmp/myimage.tar

      - name: build image and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: true
          tags: ${{ env.DEPLOY_TAG }}

      - name: upload test image
        uses: actions/upload-artifact@v3
        with:
          name: test_image
          path: /tmp/myimage.tar

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current branch
        uses: actions/checkout@v3
      - name: login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: run container in test mode
        run: |
          echo "hello test"
