on: 
  pull_request:
    branches:
      - main

env:
  TEST_TAG: wgwergwegwer/exlex-nginx:test
  DEPLOY_TAG: wgwergwegwer/exlex-nginx:latest

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: checkout to current branch
        uses: actions/checkout@v3

      - name: connect tools to build image
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: build test image and push to docker hub
        uses: docker/build-push-action@v4
        with:
          context: .
          load: false
          push: true
          tags: ${{ env.TEST_TAG }}

      - name: build production image
        uses: docker/build-push-action@v4
        with:
          context: .
          platforms: linux/amd64
          push: false
          load: false
          outputs: type=docker,dest=/tmp/prod_image.tar
          tags: ${{ env.DEPLOY_TAG }}

      - name: save prod image
        uses: actions/upload-artifact@v3
        with:
          name: prod_image
          path: /tmp/prod_image.tar

  test:
    runs-on: ubuntu-latest
    container:
      image: wgwergwegwer/exlex-nginx:test
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.github_token }}
    needs:
      - docker
    steps:
      - name: checkout to current branch
        run: nginx -t

  deploy:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: download prod image
        uses: actions/download-artifact@v3
        with:
          name: prod_image
          path: /tmp/prod_image.tar

      - name: login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Load image
        run: |
          docker load --input /tmp/prod_image.tar
          docker image ls -a

